Extension { #name : #FQPropertyQueryParametersPresenter }

{ #category : #'*Famix-Queries-Browser-Tests' }
FQPropertyQueryParametersPresenter >> comparators [
	^ comparators
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQPropertyQueryParametersPresenter >> properties [
	^ properties
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQPropertyQueryParametersPresenter >> queryBuilder [
	^ queryBuilder
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQPropertyQueryParametersPresenter >> valueInput [
	^ valueInput
]
