Extension { #name : #FQQueriesCombinationPresenter }

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueriesCombinationPresenter >> browser [
	^ browser
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueriesCombinationPresenter >> combinationsDroplist [
	^ combinationsDroplist
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueriesCombinationPresenter >> parentQueries [
	^ parentQueries
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueriesCombinationPresenter >> queriesTree [
	^ queriesTree
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueriesCombinationPresenter >> resultList [
	^ resultList
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueriesCombinationPresenter >> toolBar [
	^ toolBar
]
