Extension { #name : #FQQueryCreationPresenter }

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> browser [
	^ browser
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> queryCode [
	^ queryCode
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> queryConfigurationPresenter [
	^ queryConfigurationPresenter
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> queryTypesDropList [
	^ queryTypesDropList
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> resultList [
	^ resultList
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> resultListTitle [
	^ resultListTitle
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> toolBar [
	^ toolBar
]
