Extension { #name : #FQQueryCreationPresenter }

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> queryCode [
	^ queryCode
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> queryConfigurationPresenter [
	^ queryConfigurationPresenter
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> queryConfigurationPresenter: anObject [
	queryConfigurationPresenter := anObject
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> queryTypesDropList [
	^ queryTypesDropList
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> resultList [
	^ resultList
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryCreationPresenter >> toolBar [
	^ toolBar
]
