Extension { #name : #FQQueryConfigurationPresenter }

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryConfigurationPresenter >> firstParameter [
	^ firstParameter
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryConfigurationPresenter >> firstParameter: anObject [
	firstParameter := anObject
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryConfigurationPresenter >> secondParameter [
	^ secondParameter
]

{ #category : #'*Famix-Queries-Browser-Tests' }
FQQueryConfigurationPresenter >> secondParameter: anObject [
	^ secondParameter := anObject
]
