# This workflows runs your tests as specified in your .smalltalk.ston configuration file.

name: Run tests

on: [ push, pull_request ]

jobs:
  run:
    uses: moosetechnology/.github/.github/workflows/run-tests.yml@main
    secrets: inherit
